name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1  # Use actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install Node.js
        run: |
          choco install nodejs-lts
          npm install -g @aws-amplify/cli

      - name: Pull AWS Amplify backend
        run: |
          aws configure set aws_access_key_id AKIAYEIIWMRSDTCYPTW5
          aws configure set aws_secret_access_key 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
          aws configure set default.region us-east-1
          amplify init --appId du2y1as979iad --envName dev
          amplify --version
          amplify pull

      # Add more steps as needed for your build process
