name: Pull Amplify Backend

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  amplify_pull:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Amplify CLI
        run: |
          curl -sL https://aws-amplify.github.io/amplify-cli/install-win -o install.cmd
          install.cmd
          
      - name: Pull Amplify Backend
        run: |
          amplify pull --appId du2y1as979iad --envName dev |
          printf 'android\napp/src/main/res\nY\n'  # Providing the necessary inputs
