name: Amplify Pull

on:
  push: # This workflow will be triggered on every push to the repository
    branches:
      - main # Adjust the branch name as needed

jobs:
  amplify_pull:
    runs-on: windows-latest # Use a Windows environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v2 # Checkout your repository code

    - name: Install Amplify CLI and pull project
      run: |
        curl -sL https://aws-amplify.github.io/amplify-cli/install-win -o install.cmd && install.cmd
        amplify pull --appId du2y1as979iad --envName dev
