
name: Test
on: 
 push:
    branches:
    - main
 pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v1
      
      - name: Upload Binary file to Google Drive folder 
        uses: Jodebu/upload-to-drive@v1
        with:
          target: README.md
          credentials: ${{ secrets.G_DRIVE }}
          folder: 1H-N4IHU4vnmcXOB8AFlZGe2mA2ziqCqz
