name: Amplify Pull

on:
  push:
    branches:
      - main  # Adjust to the branch you want to trigger the workflow on

jobs:
  amplify-pull:
    runs-on: windows-latest  # Use the latest available Windows runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Adjust to the Node.js version you need
      - name: Install Amplify CLI
        run: |
          #aws configure set aws_access_key_id AKIAYEIIWMRSDTCYPTW5
          #aws configure set aws_secret_access_key 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
          #aws configure set default.region us-west-1
          #curl -sL https://aws-amplify.github.io/amplify-cli/install-win -o install.cmd
          cmd /c install.cmd
      - name: Pull Amplify Project
        run: |
          cmd /c c:\Users\runneradmin\.amplify\bin\amplify pull --appId du2y1as979iad --envName dev -y
