
name: Test
on: 
 push:
    branches:
    - main
 pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Upload Binary file to Google Drive folder 
        uses: Jodebu/upload-to-drive@v2
        with:
          target: README.md
          credentials: ${{ secrets.G_DRIVE }}
          folder: 1efAmc76e3J5Gq2y3rv5lR25JIMaNTYEf
